### ISSUE TITLE
Capture.list() won't pick up Microsoft Kinect v1 as an input device

### ISSUE THREAD

**Issue by DannyRoberts95** [processing/processing-video#105]
Using: 

- Mac OS Mojave 10.14.3 
- Processing Version 3.5.3

I am trying to use the kinect v1 video feed with the processing video library. When I access the feed via simple the OpenNI or OpenKinect libraries I am able to display the feed, so I know the Kinect is functioning correctly. 

However when trying to use the kinect as an input for the processing video library it does not appear in the capture list. The only available devices are my inbuilt facetime webcam. Does anyone know how one might fix this problem or work around it?

Thanks!

**Comment by codeanticode** [comment]
@DannyRoberts95 Is this with the latest stable version of the library or with the [2.0-beta1](https://github.com/processing/processing-video/releases/tag/r3-v2.0-beta1)?

**Comment by DannyRoberts95** [comment]
Hey, I believe it is the latest stable version as it is the one that is imported by processing by default. Is there a notable difference between the two?

**Comment by codeanticode** [comment]
Yes, people have reported that performance of the new version is substantially better. Also, since it is based on a much recent version of the gstreamer framework, support for newer capture devices might also be improved.

**Comment by symrin** [comment]
Did you ever figure out how to fix this issue? I am facing the same problem.

**Comment by codeanticode** [comment]
I don't think you will be able to get the Kinect camera from Capture.list(), but perhaps you could see if it is possible to construct a custom GStreamer pipeline to get the video from the Kinect, see these couple of issues that go over that topic:

https://github.com/processing/processing-video/issues/106#issuecomment-517312134

https://github.com/processing/processing-video/issues/26#issuecomment-415000840

The Capture object will fully support custom pipelines in the stable v2.0 release of the library.

**Comment by codeanticode** [comment]
The pipeline parsing functionality is available in the latest version of the video library (see capture/CustomPipeline), which should help capturing video from specialized capture hardware.
