### ISSUE TITLE
Automatically bundle gstreamer libs into video library package

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-video#108]
Right now, the various gstreamer binary library files need to be bundled manually for the Mac and windows platforms using the installers provided [here](https://gstreamer.freedesktop.org/data/pkg/windows/) and [here](https://gstreamer.freedesktop.org/data/pkg/osx/). One first need to download and run the installer, find where the installer copied the files, and then include only those needed by the video library into the library package. It would make the build process much more streamlined and easier to follow by other people if these bundling tasks could be automated as part of the build script.

**Comment by neilcsmith-net** [comment]
Why not use a system install?  Multiple times on the forum now I've helped people with issues where being able to upgrade the bundled GStreamer would have helped.  Surely would work better to bundle the libraries, if at all, as an optional part of the export process.

IIRC at least the old version of the library had a license conflict too, possibly current as well - this would help here.

**Comment by codeanticode** [comment]
Fixed with the mac scripts: https://github.com/processing/processing-video/tree/master/scripts, windows does not need anything special, we just bundle all original dlls :-)
