### ISSUE TITLE
2.0-beta1 wrong path closes without errors (relative paths don't work?)

### ISSUE THREAD

**Issue by hamoid** [processing/processing-video#110]
It seems like trying to load an inexisting file closes the program without any errors.

    movie = new Movie(this, "fgstdrsfstr");

In this case the bogus file name may be easy to detect. But when I converted

    foto = loadImage("../images/foto1.jpg");

into

    movie = new Video(this, "../videos/video1.mp4");

the program would just close. I had to comment out all lines of code to find out which line was the problem. This shows a possible second problem: relative paths work for `loadImage` but don't for `new Video`. If I replace the path with an absolute path it works fine.

Maybe someone can try these two issue to confirm? (wrong path and relative path)

**Comment by codeanticode** [comment]
@hamoid Does this still happen with the [latest beta](https://github.com/processing/processing-video/releases/tag/r5-v2.0-beta3)?

**Comment by hamoid** [comment]
Works great. 
* Bogus paths are shown in the error area of Processing.
* I could put `launch2.mp4` directly inside the `Movie/` folder, then change the examples to target `../../launch2.mp4` and they worked fine.

Nice!

**Comment by codeanticode** [comment]
Awesome, thanks for checking!
