### ISSUE TITLE
Upgrade to JNA 5.2.0+ and gst1-java-core 1.1.0

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing-video#120]
Mainly a note that the gst1-java-core library as of 1.0 requires JNA 5.2.0+.  You're likely to get spurious problems using JNA 4.2.0.  Unfortunately using Ant you're missing this dependency problem.  You could look at integrating Ivy to download the dependencies rather than check them in.

Worth also upgrading gst1-java-core for a few bug fixes.

**Comment by codeanticode** [comment]
Implemented with https://github.com/processing/processing-video/pull/123/commits/9395972d73fc31f0309d540189c9583332d1cb8a
