### ISSUE TITLE
Reduce size of bundled GStreamer libs

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-video#128]
The beta4 video library package including the mac, win32, and win64 binaries of GStreamer 1.16.0 is ~230 mb in size (down from 280 in beta 3). It would be good to reduce if further.

[This script](https://github.com/processing/processing-video/blob/master/scripts/macosx_remove_extra_libs.py) needs to be tweaked to further reduce the size on mac. For example, a few libraries (including libav) are duplicated because some plugins refer to the same lib but with different name. The packages image for Mac is not yet available for 1.16, that would simplify removing unneeded packages.

The gstreamer-net plugins are probably not necessary for typical use, and they occupy 50 mb on windows (only 7 on mac?) so they could be removed. There are some dependencies to be solved though. 

The library now gives priority to a system install of GStreamer if available, this will allow users who need a full GStreamer to simply install it and override the copy bundled with the library.

**Comment by neilcsmith-net** [comment]
Why install at all?  Helper support pointing to the upstream GStreamer installers would surely be far easier?
