### ISSUE TITLE
Export video doesn't work nice

### ISSUE THREAD

**Issue by knupel** [processing/processing-video#13]
OS 10.9.4 / iMac 2012 / Processing 221 and 302.
I found a very weird thing the last day when I try to export video.

When I write simply code, the exportation don't work, but when copy-paste the code in a new sketch the exportation work. Same when I zip the sketch and I unzip open in Processing and export the exportation work.
it's weird isn't it ?

the simply code

```
import processing.video.*;
Capture video;

void setup() {
  size(640,480) ;
  video = new Capture(this, width, height);
  video.start() ;
}

void draw() {
    if (video.available()) { 
    // Reads the new frame
    video.read(); 
  } 
  image(video, 0, 0); 
}
```

**Comment by codeanticode** [comment]
Export application works with latest version of video library (2.2.x) and Processing (4.1.1)
