### ISSUE TITLE
NullPointerException - Linux capture with v2 beta 4

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing-video#130]
I just tried updating to beta 4 and am getting a NullPointerException trying any capture example.  This is on an Ubuntu 18.04 machine.  beta 3 is fine, so seems to be something that changed between.  Won't have a chance to delve further into this for a week or so, but can dig around after that if needed.

**Comment by jaegonlee** [comment]
Have you tried to set the camera name?
I had same issue on macOS 10.15, but there's no problem after setting the camera name.
The default camera is set automatically on beta 3, but not on beta 4.

**Comment by neilcsmith-net** [comment]
@jaegonlee yes that is indeed the cause of the bug. Haven't tried setting the device name / pipeline which should fix it - aside from feeding in issues I don't have a use for the library personally.
