### ISSUE TITLE
Issue with video library on Raspberrypi x86

### ISSUE THREAD

**Issue by f41ardu** [processing/processing-video#132]
The latest video library won't work on my x86 based RaspberryPi (latest version, uptodate) using Processing 3.5.3. 
loop Sketch run but window stay black, no error message. What is missing? 
Raspberry -> 
Linux version 4.19.0-6-686-pae (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20)

**Comment by codeanticode** [comment]
This video library is designed to run on laptop or desktop computers running Windows, Linux, or Mac. Please use [GLVideo](https://github.com/gohai/processing-glvideo) on RPi.

**Comment by codeanticode** [comment]
Another user has reported that the latest beta of the v2.0 of this video library works on RPi (#137) but haven't tested myself. Need to look into this further.
