### ISSUE TITLE
Processing Video on Mac

### ISSUE THREAD

**Issue by KazimWalji** [processing/processing-video#152]
I deleted and re dowbloaded processing 3 times and followed differnet tutorials. Whenever I try showing video a gray screen shows up, my camera works as i use factime. Here is my code:

import processing.video.*;
// Step 1. Import the video library.
import processing.video.*;

//Step 2. Declare a capture object.
Capture video;

// Step 5. Read from the camera when a new image is available!
void captureEvent(Capture video) {
  video.read();
}

void setup() {  
  size(320, 240);
  
  // Step 3. Initialize Capture object.
  video = new Capture(this,320, 240);
  
  // Step 4. Start the capturing process.
  video.start();
}

// Step 6. Display the image.
void draw() {  
image(video, 0, 0);
}

**Comment by MTwiko** [comment]
Duplicate of #134

**Comment by christo** [comment]
@codeanticode this should be closed

**Comment by benfry** [comment]
Closing as duplicate of #134.
