### ISSUE TITLE
Video loading triggers "Invalid memory access" error 

### ISSUE THREAD

**Issue by nicolasbd** [processing/processing-video#158]
## Description

When loading some simple video examples from the Video or OpenCV library, Processing triggers an `Invalid memory access` error on line `video = new Movie(this, "transit.mov");`

```import processing.video.*;

Movie movie;

void setup() {
  size(640, 360);
  background(0);
  // Load and play the video in a loop
  movie = new Movie(this, "transit.mov");
  movie.loop();
}
```

## Expected Behavior
The video should be loaded and the sketch should display it 

## Current Behavior
`Invalid memory access` error prevents the sketch to run 

## Steps to Reproduce

1. Install the Video library in Processing 4
2. Open the example under : Examples > Libraries > Video > Movie > Loop 
3. Try to run the sketch

## Your Environment

* Processing version: 4.0a1
* Operating System and OS version: Windows 10 Pro, 64 bits, 16GB ram 
* Other information: Java JDK 11.0.3

## Possible Causes / Solutions
* No idea what's going on
* Works on Processing 3

**Comment by benfry** [comment]
(Moving this to the video repo…)

**Comment by nicolasbd** [comment]
Hello @sampottinger 
Still have this issue on Windows 10 x64 v4.1.1 
When I run Processing for the first time, I get this security alert from Windows : 

![image](https://user-images.githubusercontent.com/1822081/211059182-f00b31cb-c8b1-4282-9ce4-215eb7e5d44c.png)

Could it be related ?

**Comment by sampottinger** [comment]
Hello! I think this is unrelated. See https://github.com/processing/processing4/issues/25.

**Comment by nicolasbd** [comment]
Alright, thanks
But then I have no clue what's causing this error 🤷

**Comment by sampottinger** [comment]
@codeanticode did you get a chance to dig into this any more?

**Comment by codeanticode** [comment]
@sampottinger not yet, but was able to get some android work done, so will look at the video library next :-)

**Comment by sampottinger** [comment]
Awesome thanks!

**Comment by codeanticode** [comment]
@sampottinger Unfortunately I cannot replicate this issue

@nicolasbd What version of the video library are you using?

**Comment by nicolasbd** [comment]
@codeanticode ahh good point, since I made updates from old versions of Processing, I had an old version of the lib installed 

But in the tools management interface it still shows the old one, although I updated the new one and it now seems to work

**Comment by nicolasbd** [comment]
Ok so I just removed the Documents/Processing/libraries/video folder (dunno why I had to restart my computer for that because it seemed to be in use even when I closed Processing), and then I reinstalled the "Video Library for Processing 4" from the Tools manager
I can close the ticket, thanks for your help @codeanticode and @sampottinger 

Improvements, if needed, would be in tools / library management between Processing version updates
