### ISSUE TITLE
Processing video library can’t display human figure in a video with green background

### ISSUE THREAD

**Issue by EmbraceLife** [processing/processing-video#163]
Hi everyone,

I am using the following code to play the welcoming p5js [video](https://github.com/processing/p5.js-video/blob/gh-pages/assets/video.mp4) which is green background with human figures talking. The problem is that I can only see green canvas (and hear voices) without human figures. I don't understand where went wrong. Could anyone help? Thanks

The following is my code.

```
import processing.video.*;

Movie movie;

void setup() {
  size(320, 240);
  movie = new Movie(this, "video.mp4");
  movie.play();
}

void draw() {

  if (movie.available()){

    movie.read(); 
  }

  image(movie, 0, 0);
}

void keyPressed(){
  if (key == CODED){
    
    if (keyCode == UP){
      println("movie length: " + movie.duration());
    }
  }
}
```

**Comment by StanLepunK** [comment]
Hello, Ithink the better place for this post is on the forum https://discourse.processing.org/ github is more for the improvement or bug report.
