### ISSUE TITLE
Playing movie backwards with loop()

### ISSUE THREAD

**Issue by shiffman** [processing/processing-video#17]
A movie will play backwards (if the codec supports) it.  However, if you call `loop()` it will not return to the end and continue to play backwards but throws the following error:

```
(Processing core video:9242): GStreamer-WARNING **: wrong STREAM_LOCK count 0
```

This was discovered when checking out #16.

**Comment by arneboon** [comment]
For workaround see:
https://discourse.processing.org/t/movie-library-reverse-video-looping-example/11963

**Comment by codeanticode** [comment]
Backward playback works as expected with the latest version of the library (2.2.x)
