### ISSUE TITLE
#134 Solution does not work for MacOS Big Sur

### ISSUE THREAD

**Issue by highjeans** [processing/processing-video#174]
I am trying the solution proposed by @ihaveaccount on issue #134 but it doesn't work for me. I am using MacOS 11.1 with processing 3.5.4.

**Comment by highjeans** [comment]
> v2 library works on catalina, thank you @codeanticode
> 
> How to install
> 
> * replace ~/Documents/processing/libraries/video with "video" folder from https://github.com/processing/processing-video/releases/tag/r6-v2.0-beta4
> * open console, cd to ~/Documents/processing/libraries/video/library/macosx
> 
> $ xattr -p com.apple.quarantine libavcodec.58.35.100.dylib
> it will return string like this:
> 0081;5dc1bfaa;Chrome;78F18F7D-3F71-4E55-8D58-BAB946AB4707
> 
> replace 0081 with 00c1 and copy string
> 
> then replace STRING in the following command with your string
> $ xattr -w com.apple.quarantine "STRING" *.dylib
> it will fix all libraries in this folder
> 
> then cd to gstreamer-1.0/ and run command again

**Comment by benfry** [comment]
The bug fix for #134 hasn't been released yet. As stated in that thread, it will be in 4.0a3. The video library mostly works, but more changes are necessary.

**Comment by highjeans** [comment]
@benfry  Is Processing 4 out yet?
