### ISSUE TITLE
Mac os11.2.3 can not work

### ISSUE THREAD

**Issue by Samuelzhao919812375** [processing/processing-video#183]
I used the latest version of the video library(2.0-beta5)
and cannot load the my camera
2021-03-22 00:55:23.865 java[1255:41131] -[Stream xpcConnectionWasInvalidated:] invalidation
like this

**Comment by codeanticode** [comment]
@Samuelzhao919812375 What about using the [latest 2.0 release](https://github.com/processing/processing-video/releases/tag/latest)?
