### ISSUE TITLE
GStreamer update breaks video playback on Arch Linux

### ISSUE THREAD

**Issue by kflak** [processing/processing-video#195]
## Description
After the update to GStreamer 1.20.0-1 I am no longer able to play back video on any of my Arch Linux systems. I suspect that this will soon render any video work on Linux impossible as soon as the other distros catch up :grimacing: 

## Expected Behavior
To be able to play back video as described in [this tutorial](https://processing.org/tutorials/video/#recorded-video)

## Current Behavior
Getting a white window and the error:
```
(Processing core video:105730): GStreamer-Base-CRITICAL **: 16:34:27.150: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaap
ipostproc0:sink
```

## Steps to Reproduce

1. Run this code from the Processing IDE or from Nvim with the vim-processing plugin:
```processing
import processing.video.*;

Movie movie;

void setup(){
  size(320, 240);
  movie = new Movie(this, "sanskarpromo.mp4");
  movie.play();
}

void movieEvent(Movie movie){
  movie.read();
}

void draw(){
  image(movie, 0, 0);
}
```

## Your Environment

 

* Processing version: 1280
* Operating System and OS version: Linux t480s 5.15.2130.realtime1-1-rt-lts processing/processing4#1 SMP PREEMPT_RT Thu, 10 Feb 2022 15:14:13 +0000 x86_64 GNU/Linux

* Other information: Gstreamer v. 1.20.0-1.
* See also this issue I opened for openFrameworks: https://github.com/openframeworks/openFrameworks/issues/6871. Same backend, same problem... Had to roll one of my systems back to early February and gstreamer 1.18 to solve the issue.

**Comment by benfry** [comment]
Another reason we (usually) include the binaries with the library, because we want the video library to work out of the box without users needing to install or understand dependencies. I wish they hadn't been removed on Linux, hopefully we can get that sorted for a future release. 

And of course, we need to deal with whatever changes are necessary for 1.20, but since nobody is actively maintaining this library, it would be better to have the old libraries in there so that things continue working in the meantime.

**Comment by kflak** [comment]
Thanks for the quick answer! I have flagged this to the aur maintainers, hope they will be able to offer a compatible gstreamer package. Would help out my openFrameworks situation as well :slightly_smiling_face:

**Comment by kflak** [comment]
Hi @letorbi, I haven't had the chance to test this on the system with gstreamer 0.18, but on the one with 0.20 I get the same error when using the official package:
```
Processing video library using GStreamer 1.20.0

(Processing core video:57306): GStreamer-Base-CRITICAL **: 15:08:40.280: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink
```
This happens to both .mp4 and .mov files, that play back flawlessly in my other video apps (mpv, mainly), but not in openFrameworks and Processing. Will look into the possibility of sharing them. Do you have any drive I could upload any of these to?

**Comment by letorbi** [comment]
@kflak Thanks for testing with the official package. You could use a service like [WeTransfer](https://wetransfer.com/) to share the video with us.

@benfry If the problem also occurs with the official package, it does not seem to be related to my AUR package. Or am I missing something? I just want to make sure, that my package is not the root of this problem...

**Comment by kflak** [comment]
OK, put this up on wetransfer together with my minimal test program: https://we.tl/t-mBQmPbEUvJ The link expires in a week. Hope to have some time later this week to test this on my other machine that runs gstreamer 0.18.

**Comment by letorbi** [comment]
I was able to run the test program you've provided without any problems on Wayland and X11. I've checked with the official release as well as with the AUR package.

Maybe the problem is a result of your specific system configuration (installed packages, graphics driver, ...just guessing).

Right now, I would say that the problem is not related to the processing AUR package or Processing in general. Since the problem occurred just after a Gestreamer update, it might be an idea to ask the Gstreamer guys for help. Maybe they know about some regressions and/or can fix the bug...

**Comment by letorbi** [comment]
@kflak I hope you can find the issue. Good luck to you. Just an idea: I was testing on GNOME, so it might be desktop environment problem.

Regarding the GPU: I've tested on a NVIDIA 1080 with the proprietary driver.

**Comment by codeanticode** [comment]
Please try this new release of the video library:

https://github.com/processing/processing-video/releases/tag/r9-2.1.0

It bundles an amc64 build of GStreamer 1.16, which should override the system-wide GStreamer that's causing trouble.

**Comment by kflak** [comment]
Works beautifully! Thank you so much!

**Comment by kflak** [comment]
> @kflak I hope you can find the issue. Good luck to you. Just an idea: I was testing on GNOME, so it might be a desktop environment problem.
> 
> Regarding the GPU: I've tested on a NVIDIA 1080 with the proprietary driver.

I am using bspwm, but had the same issue on XFCE4 as well. Tried on both a laptop with internal Intel GPU as well as one with and AMD GPU, using proprietary drivers. Haven't tested it yet with NVIDIA, as I am using that laptop for production right now, and keep it rolled back.

**Comment by cherio** [comment]
A reliably reproducible test case is listed here: https://github.com/openframeworks/openFrameworks/issues/6871#issuecomment-1107940741
