### ISSUE TITLE
120fps camera on Windows - error

### ISSUE THREAD

**Issue by kkirklewski** [processing/processing-video#201]
I try to run 120fps camera in Processing 4.08b on Windows 10, but I get an error saying:

`BaseSrc: [ksvideosrc0] : Internal data stream error.`

I use basic "GettingStartedCapture" example from the new Video 2.1 library, with the setting below. I work on 144hz screen (if that matters).

`cam = new Capture(this, 320, 240, "Arducam OV9281 USB Camera", 120);`

The same sketch+setting works fine on MacBook M1 Pro, Processing 4.08b for Intel, 120fps display.

Link to the camera:
https://www.arducam.com/product/arducam-120fps-global-shutter-usb-camera-board-1mp-720p-ov9281-uvc-webcam-module-with-low-distortion-m12-lens-without-microphones-for-computer-laptop-android-device-and-raspberry-pi/

My insights:
- the camera works smooth in the browser on some camera test website
- camera runs when I don't give the last parameter ("120"), but then it looks like 10fps
- camera works with 120fps in OBS studio
- I checked on other PC computers (Windows 11 too) and I get the same error
- I get the same error with another camera (the same model)
- I'm pretty sure it's an issue with the GStreamer (a part of Video library) running on Windows, but I'm not sure how I could fix it
- I tried to run the same sketch in Processing 3.5.4 with Video 2.0 library and got the same result
- I tried to run the same sketch in Processing 3.5.4 with Video 1.0.1, this one prints a list with possible settings (below), but only the last 2 options (with 10fps) work:
`[0] "name=Arducam OV9281 USB Camera,size=1280x800,fps=100"
[1] "name=Arducam OV9281 USB Camera,size=1280x800,fps=120"
[2] "name=Arducam OV9281 USB Camera,size=1280x720,fps=120"
[3] "name=Arducam OV9281 USB Camera,size=800x600,fps=100"
[4] "name=Arducam OV9281 USB Camera,size=800x600,fps=120"
[5] "name=Arducam OV9281 USB Camera,size=640x480,fps=100"
[6] "name=Arducam OV9281 USB Camera,size=640x480,fps=120"
[7] "name=Arducam OV9281 USB Camera,size=320x240,fps=100"
[8] "name=Arducam OV9281 USB Camera,size=320x240,fps=120"
[9] "name=Arducam OV9281 USB Camera,size=1280x800,fps=10"
[10] "name=Arducam OV9281 USB Camera,size=1280x720,fps=10"
`

I would really appreciate some help from more skilled programmer.

**Comment by codeanticode** [comment]
@kkirklewski It could be the case that the GStreamer capture plugin on Windows (ksvideosrc) does not fully support all the specs of your camera. The corresponding capture plugin on Mac (avfvideosrc) is completely separate, and sounds like it offers better support for the Arducam device. One thing you can try is to launch a capture pipeline like this:

```
cam = new Capture(this, 640, 480, "pipeline:ksvideosrc device-index=0 ! video/x-raw, width=640, height=480, framerate=30/1"); 
```

trying different values for framerate, including 120/1, maybe that works better. But I don't thing we can do much from the video library itself (GStreamer has to include better support for this camera on Windows).
