### ISSUE TITLE
Cannot build due to seeming dependency on Eclipse compiler

### ISSUE THREAD

**Issue by jdf** [processing/processing-video#24]
`/Users/feinberg/tmp/processing-video/build.xml:23: Class not found: org.eclipse.jdt.core.JDTCompilerAdapter`

**Comment by codeanticode** [comment]
Hi Jonathan, do you still have this issue? I recently updated the build script so you can point to the locations where the jar dependencies are stored.

**Comment by jdf** [comment]
Because Python Mode/proessing.py can no longer build with any version of Processing past 3.0a4, I can't check this.
