### ISSUE TITLE
Not all "Apple QuickTime format" codecs are supported.

### ISSUE THREAD

**Issue by brysonian** [processing/processing-video#28]
The documentation (seen here: https://processing.org/reference/libraries/video/Movie.html) states that it can play "movies in Apple's QuickTime format" but there are a number of formats that GStreamer doesn't support, most notably ProRes. Is it worth a link to a list of supported codecs? Or should those be included directly in the documentation?

**Comment by REAS** [comment]
I'll file this over in processing/processing-docs/. Thank you for the report.
