### ISSUE TITLE
Video Issues, OPENGL Issues pages on wiki

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-video#3]
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Sunday Feb 10, 2013 at 17:00 GMT_
_Originally opened as https://github.com/processing/processing/issues/866_

---

_Original author: r...@processing.org (September 02, 2011 18:30:19)_

http://wiki.processing.org/w/Video_Issues
http://wiki.processing.org/w/OpenGL_Issues

These pages need to be reviewed and altered for the 2.0 release. The video page is linked from the reference pages on the main site, which I have updated in the source, but not yet on the site.

http://processing.org/reference/libraries/video/index.html

_Original issue: http://code.google.com/p/processing/issues/detail?id=828_

**Comment by codeanticode** [comment]
Updates about installation, and other topics are being added to the processing-video wiki.
