### ISSUE TITLE
loadPixels() with Capture failing on 3.0 and 3.0.1

### ISSUE THREAD

**Issue by shiffman** [processing/processing-video#37]
I'm not sure if this is a Processing or processing-video bug, but I'll start here and then we can move it if necessary.  The following code works perfectly with the default renderer, but crawls to a halt with `P2D` or `P3D`.  Removing `loadPixels()` also makes it runs smoothly in `P2D` or `P3D` so that seems to be the source of the problem.  Tested on Mac OS X, Processing 3.0 and 3.0.1.

``` java
import processing.video.*;

Capture cam;

void setup() {
  size(640, 480, P2D);
  String[] cameras = Capture.list();
  cam = new Capture(this, cameras[0]);
  cam.start();
}

void draw() {
  if (cam.available() == true) {
    cam.read();
  }
  image(cam, 0, 0, width, height);
  cam.loadPixels();
}
```

**Comment by MAKIO135** [comment]
Stil failing with Processing 3.1.1 on Windows 8.1

May be related but displaying cam inside a PGraphics also fails in P2D:
```
import processing.video.*;

Capture video;
PGraphics pg;

void setup() {
    size(320, 240, P2D);

    video = new Capture(this, width, height);
    video.start(); 

    pg = createGraphics(width, height);
    pg.beginDraw();
    pg.background(255, 0, 0);
    pg.endDraw();
}

void draw() {
    if (video.available()) {
        video.read();
        pg.beginDraw();
        pg.image(video, 0, 0);
        pg.endDraw();
    }

    image( pg, 0, 0);
}
```

**Comment by tolkanabroski** [comment]
Still an issues. Maybe some changes to the list method. With cameras[1] the smallest available resolution, it works again. 


>Tested on Windows 10 Processing 3.3.3

```java
import processing.video.*;

Capture cam;

void setup() {
  size(640, 480, P2D);
  String[] cameras = Capture.list();
  cam = new Capture(this, cameras[1]);
  cam.start();
}

void draw() {
  if (cam.available() == true) {
    cam.read();
  }
  image(cam, 0, 0, width, height);
  cam.loadPixels();
}  
```

**Comment by codeanticode** [comment]
@shiffman Yes, calling loadPixels() with the OpenGL renderer slows down the sketch because image data needs to be copied from GPU memory, so it is not recommended, specially for large resolutions,
