### ISSUE TITLE
video library not working. p5 3.0.1 ARMv6hf, RPI 2 B.

### ISSUE THREAD

**Issue by kroko** [processing/processing-video#38]
Hello,

Running Mirror example.

when using newest video library 1.0.1 via Contrubution Manager the error is
```
No such Gstreamer factory: v4l2src
```

when rolling back to 1.0 https://github.com/processing/processing-video/releases/tag/1 the error is
```
NoClassDefFoundError: Could not initialize class com.sun.jna.Native
```

Happens both on RASPBIAN JESSIE and RASPBIAN WHEEZY on Raspberry Pi 2 B.

Installed processing both via `curl https://processing.org/download/install-arm.sh | sudo sh` and manually.

Tried also multiple cameras that are known to work with Raspberry Pi (and are used on everyday basis).

The OSes are vanilla, no components installed only p5.

Related https://github.com/processing/processing-video/issues/35

**Comment by codeanticode** [comment]
@gohai is working on a high-performance video library for RPi, check progress [here](https://github.com/gohai/processing-glvideo).

**Comment by gohai** [comment]
@kroko Please see https://github.com/processing/processing/wiki/Raspberry-Pi#video-library-capture

**Comment by donim4rt** [comment]
Hi brother if you dont mind i found the difference here i attached 2 picture. 1st glvideo library and 2nd processing video library. In the video lib there is no directory for linuxarmv6hf but exist in glvideo lib. Could it be the problem. Thank you for your concern

Dikirim dari Yahoo Mail di Android 
 
  Pada Jum, 13 Sep 2019 pada 3:37, Gottfried Haider<notifications@github.com> menulis:   
I am no longer working on this software @donim4rt

**Comment by donim4rt** [comment]
Dikirim dari Yahoo Mail di Android 
 
  Pada Jum, 13 Sep 2019 pada 3:37, Gottfried Haider<notifications@github.com> menulis:   
I am no longer working on this software @donim4rt
