### ISSUE TITLE
List of Supported Codecs?

### ISSUE THREAD

**Issue by Sensebellum** [processing/processing-video#40]
Just getting into video with Processing 3.0

I am curious as to what codecs are supported with this library?

I am looking to playback Apple ProRes (Apple ProRes 422 Proxy specifically). However, I have only gotten H.264 to work.

Is there any extra code necessary? A list I could consult? or perhaps other video libraries that are suggested for different codecs?

I am on a Mac Pro Retina OSX 10.10

Thanks for all the great work in the meantime!

**Comment by alignedleft** [comment]
Please reference the wiki:  https://github.com/processing/processing-video/wiki#media-formats

:-)
