### ISSUE TITLE
Video not availabe on P2D or P3D

### ISSUE THREAD

**Issue by blausand** [processing/processing-video#43]
Apparently, the video playback is not available for P2D or P3D renderers on the **Raspberry Pi 2**.
This is particularly sad since that would enable the whole world to use the **keystone library** of processing for elegant projection mapping, e.g. on architecture. Instead, video has to be rendered /after/ the exact transformation of the projectors is known. (which is too late normally.)

- [ ] What exact dev steps are necessary to make gstreamer's framebuffers available for the OpenGL hardware acceleration?

**Comment by REAS** [comment]
@gohai?

**Comment by gohai** [comment]
@codeanticode and myself are working to make this happen - but not even openFramework has something like this working, so we're more excited to be breaking ground here, than sad!

If you want to give us a hand - development is happening here:

GStreamer Java bindings
https://github.com/codeanticode/gst1-java-core/commits/master

Processing-video
https://github.com/processing/processing-video/tree/gst1-java-core

openFrameworks branch to see if we can get their infrastructure to work on the Pi https://github.com/gohai/openFrameworks/commits/gstgl-fixes

Closing.
