### ISSUE TITLE
Does not work on Processing 3

### ISSUE THREAD

**Issue by GatoUVR** [processing/processing-video#47]

**Comment by kgranat** [comment]
I was able to get the processing video library working by installing it via the library manager

https://processing.org/reference/libraries/

"The following libraries are created by the Processing Foundation. The PDF Export, Network, Serial, and DXF Export libraries are distributed with Procesing. The Video and Sound libraries need to be downloaded through the Library Manager. Select "Add Library..." from the "Import Library..." submenu within the Sketch menu."
