### ISSUE TITLE
Ubuntu: IllegalArgumentException: No such Gstreamer factory: v4l2src

### ISSUE THREAD

**Issue by sejomagno** [processing/processing-video#52]
I'm using Ubuntu 15.10 and I can't use the library anymore. When I run a Sketch with Capture, the following error appears:
`IllegalArgumentException: No such Gstreamer factory: v4l2src`

I tried installing `gstreamer0.1-ffmpeg` as stated [here](http://askubuntu.com/questions/575869/how-do-i-install-gstreamer0-10-ffmpeg-on-ubuntu-14-10/707612#707612), however the error message still appears.

I also tried to install @gohai library as stated in #23, also without success. (Maybe it was not clear for me how to install it)

I can't remember when was the last time I could use the library. I have no idea what else I can do.

~~(I'm about to upgrade to 16.04 but I don't think that will help)~~
The update didn't work. Any ideas of what can be done?

**Comment by gohai** [comment]
@sejomagno Which hardware are you running this on? Raspberry Pi?

**Comment by sejomagno** [comment]
@gohai Hi! Thanks for answering!

It is a laptop, Dell Inspiron 14 3000. 
Processor: Intel® Core™ i5-5200U CPU @ 2.20GHz × 4
Graphics card: Intel® HD Graphics 5500 (Broadwell GT2) 
With 4GB of RAM

Running Ubuntu 16.04 (64-bit)

**Comment by gohai** [comment]
Your problem is that you don't have the v4l2src plugin for gstreamer0.10 installed. Try installing `gstreamer0.10-plugins-good`, or similar. In any way, that's an issue with your distribution not the software.

**Comment by sejomagno** [comment]
It worked!
Sorry, I knew it had to do with my distribution, however I couldn't find what was the missing dependency. 
Thank you very much for pointing me in the right direction!

**Comment by PRTK25** [comment]
I am facing the similar issue on ubuntu 17.04. I have also installed gstreamer1.0-plugins-good. Any idea how to resolve?
