### ISSUE TITLE
No pipelines and no compatible with Processing 3

### ISSUE THREAD

**Issue by Provoo** [processing/processing-video#53]
I have to add the processing lib GSVideo to use the pipelines, but it is no more under maintenance and also I can't use it anymore with Processing 3 because it is no more compatible with the core.

![processingerror2](https://cloud.githubusercontent.com/assets/4282730/18611701/3213df1e-7d07-11e6-92e2-2f03ed314b59.png)
![processingerror](https://cloud.githubusercontent.com/assets/4282730/18611702/321632dc-7d07-11e6-8393-e5447cbcb390.png)

**Comment by codeanticode** [comment]
@Provoo [The latest beta](https://github.com/processing/processing-docs) is incorporating support for custom pipelines, see this [new example](https://github.com/processing/processing-video/blob/master/examples/Capture/CustomPipeline/CustomPipeline.pde). The functionality will be completed in the upcoming stable v2.0 release.

**Comment by codeanticode** [comment]
Custom pipelines and recent gstreamer libs included in Processing 3-compatible 2.0 release from some ago. Closing the issue.
