### ISSUE TITLE
using processing for 3D image mapping

### ISSUE THREAD

**Issue by mkeyno** [processing/processing-video#57]
hi All
first of all I'm so sorry to open ticket for my question but I really appreciated if you could direct me to correct links or track
actually I'm Arduino Neopixel fan and tried to run the spherical POV. For run POV, each image should be converted to the number of lines which is used in each revolution , I think convert the planner POV must not be so hard for processing to pixelizid in lines but I don't now how to map an image on spherical and then converted to image lines
thanks

**Comment by codeanticode** [comment]
@mkeyno [The Processing forum](https://discourse.processing.org/) is a good place to ask these more general questions. Good luck!
