### ISSUE TITLE
Movie.volume() is public but undocumented (enhancement)

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing-video#58]
In processing.video, the method `Movie.volume()` is defined as public on [Movie.java line 574](https://github.com/processing/processing-video/blob/6c7e07bc612fc6d5f3e129841638a0573f46dc2a/src/processing/video/Movie.java#L574).

It would be nice to add volume() to the public documentation: `volume()` is not listed on the [Movie reference](https://processing.org/reference/libraries/video/Movie.html), nor on the [Video library index](https://www.processing.org/reference/libraries/video/). 

---

Forum posts have noted for several years that Movie.volume() is public but undocumented: [1](https://forum.processing.org/one/topic/movie-volume-control.html), [2](https://forum.processing.org/two/discussion/118/the-library-video-you-can-put-mute-the-audio), [3](https://forum.processing.org/two/discussion/18358/sound-level-controled-by-processing-program).

**Comment by codeanticode** [comment]
@REAS The Movie and Capture class include some undocumented functions. This perhaps should be re-opened in https://github.com/processing/processing-docs

**Comment by REAS** [comment]
OK, I created a new Issue in processing/processing-docs here: https://github.com/processing/processing-docs/issues/771
