### ISSUE TITLE
.width and .height are 0 when use Capture.list() array

### ISSUE THREAD

**Issue by botikho** [processing/processing-video#60]
When I try to use "Capture.list()[0]" in line "video = new Capture(this);", it returns "0" for both video.width and video.height variables later. So I have to manually type "video = new Capture(this, 1280, 720);" but I want to run this code on my both computers with different camera resolutions using just the first maximum resolution with "Capture.list()[0]".

**Comment by botikho** [comment]
Ha-ha, just found the problem. Sorry.  
int w = int(video.width);
int h = int(video.height);

**Comment by GoToLoop** [comment]
https://forum.Processing.org/two/discussion/18536/opencv-problem-with-bootcamp#Item_1

**Comment by codeanticode** [comment]
[In the latest beta](https://github.com/processing/processing-video/releases/tag/r6-v2.0-beta4) of the video library, Capture.list() does no longer returns the list of cameras with all their supported resolutions, but just one entry per camera. You can use any resolution you want for capture, the library will downscale/upscale the video stream accordingly.
