### ISSUE TITLE
video library processing 3.2.1 bug

### ISSUE THREAD

**Issue by Felix-56** [processing/processing-video#61]
Hello,
Here is my problem, I installed the video library for processing ("GStreamer-based video library for Processing") yesterday, but it isn't working.
When I run any examples (here it's about the "Loop" example), I've got this bug : 
**" A library used by this sketch is not installed properly. A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit application. "**
I also tried to run it with a 32-bit version, it doesn't change anything.
Is anybody has an idea ?

**Comment by Felix-56** [comment]
Ok, I just moved the "Processing" folder which contains all the libraries at this location : "C:\". Now it works, but I don't know why, I can't explain it.

**Comment by GoToLoop** [comment]
"%ProgramFiles%" is a system-protected folder. And Processing isn't actually installed on the OS, but rather thrown in some folder. Therefore it lacks access privileges like programs installed via installers.

**Comment by Felix-56** [comment]
Ok, I understand. Thank you
