### ISSUE TITLE
How should i paste the folder in library. Not working with name "video"

### ISSUE THREAD

**Issue by AbhishekParadox** [processing/processing-video#62]

**Comment by laurabrooks** [comment]
see kgranat's answer to issue #47, I had the same problem but this worked.

<img width="385" alt="capture" src="https://cloud.githubusercontent.com/assets/10619715/24083818/f65ad9ee-0cb4-11e7-9042-03db3c022ff7.PNG">

**Comment by codeanticode** [comment]
Closing as it seems solved.
