### ISSUE TITLE
The Processing video library does not work on my Mac Air laptop running El Capitan

### ISSUE THREAD

**Issue by JeanineMeyer** [processing/processing-video#63]
The sketch works on my iMac desktop running Yosemite.
But on the laptop running El Capitan, there are no errors, the program starts, 
the video loads and starts with audio, but then the audio stops working.

[collageA.zip](https://github.com/processing/processing-video/files/588123/collageA.zip)

**Comment by codeanticode** [comment]
I tried your sketch on Mojave and works well, using the [latest beta](https://github.com/processing/processing-video/releases/tag/r6-v2.0-beta4) of the video library. I'm going to close this issue, but you can reopen if you still have trouble playing your videos.
