### ISSUE TITLE
Processing 3.2.3 with Blackmagic Decklink

### ISSUE THREAD

**Issue by Debileptiker69** [processing/processing-video#65]
Hi,
there is no way to capture the videostream in 1080i50 from the input of the Blackmagic card to processing. I'm looking for solutions everywhere and found nothing. I read about GStreamer, but don't understand anything. Is there a possible way yet to solve my problem?

**Comment by cacheflowe** [comment]
Unless the capture card can register as a webcam to the operating system, there's no way to use Processing's video library to do this. I would recommend an El Gato Camlink for capturing an HDMI video in Processing, or use ffmpeg's video capture tools to pull in a video stream from specialized hardware like this.

**Comment by codeanticode** [comment]
Support for custom pipelines is being added to the library, and should be fully implemented in the upcoming stable release. This other issue discusses the topic with a similar hardware:

https://github.com/processing/processing-video/issues/26

**Comment by codeanticode** [comment]
The pipeline parsing functionality is available in the latest version of the video library (see capture/CustomPipeline), which should help capturing video from specialized capture hardware.
