### ISSUE TITLE
Video Library

### ISSUE THREAD

**Issue by rhadrup** [processing/processing-video#67]
I get this message when using the GS video library. (Processing 3, Windows 10)
"A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application."

**Comment by ventilator** [comment]
The same here, when trying to run the demo code from https://processing.org/reference/libraries/video/Capture.html on Windows7, 32bit. Only that the failure message says
"A library relies on native code that's not available.
Or only works properly when the sketch is run as a 64-bit application.
"

**Comment by rhadrup** [comment]
I reinstalled Processing to another folder, avoiding the space in 'Program Files' - it helped (or it might have been the path to sketches that had a similar problem)

**Comment by hamoid** [comment]
Good that it worked! Could you close this issue @rhadrup ? :)
