### ISSUE TITLE
Please change macosx64 folder name to macosx

### ISSUE THREAD

**Issue by benfry** [processing/processing-video#70]
Because the macosx64 folder name is used, the PDE will try to export 32- and 64-bit versions of the app, causing some confusion internally. Since 32-bit doesn't exist on the Mac (anymore), we should probably just use macosx for this one.

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-video/commit/218eebec8f87c90c5a96a2347407b1d7d7d74aa7
