### ISSUE TITLE
Ubuntu 16.10 no longer supports gstreamer0.10

### ISSUE THREAD

**Issue by nekketsuuu** [processing/processing-video#71]
On Ubuntu 16.04, we should install `libgstreamer0.10-dev` to use processing-video (look at #69).

However, on Ubuntu 16.10, they are no longer provided, and only packages of gstreamer 1.0 series are provided. And GStreamer says "GStreamer 1.x has been the main stable series since 2012. GStreamer 0.10 is no longer maintained." ([link](https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/getting.html))

And processing-video didn't run with gstreamer 1.0. It wrote out the following error messages (processing 3.3.2, processing-video 1.0.1).

```
UnsatisfiedLinkError: Error looking up function 'gst_date_get_type': /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so: undefined symbol: gst_date_get_type
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
```

This would be because processing-video uses [gstreamer-java](https://github.com/gstreamer-java/gstreamer-java). It says "Current version of the gstreamer-java is NOT compatible with: GStreamer 1.0 or above. this means the last usable version are GStreamer 0.10." ([link](https://code.google.com/archive/p/gstreamer-java/))

How about using [gst1-java-core](https://github.com/gstreamer-java/gst1-java-core) instead of gstreamer-java?

* Related links
    * https://launchpad.net/ubuntu/yakkety/+source/gstreamer0.10
    * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802812
* For the moment, there is a dirty workaround [here](https://github.com/toggl/toggldesktop/issues/1894#issuecomment-254427913), which using .deb files of gstreamer 0.10 for Ubuntu 16.04.

**Comment by hamoid** [comment]
Not only Ubuntu, but ArchLinux is also getting rid of gstreamer0.10. What's the state of the https://github.com/processing/processing-video/tree/gstreamer1.x branch?

**Comment by hamoid** [comment]
I see that the gst1-java-core branch uses a 0.9 snapshot from one year ago. There's a new one 5 months old (December 1st 2016) which has tons of fixes. I wish I had time to update the gst1-java-core jar and see what happens. https://github.com/gstreamer-java/gst1-java-core/releases

**Comment by hamoid** [comment]
Since Video stopped working after gstreamer0.10 was removed, I cloned this repo, switched to the gst1-java-core branch, updated jna.jar and downloaded the latest gst1-java-core binary, and unfortunately does not build. The number of issues is not large, but I'm not familiar with gstreamer. Some method signatures have changed and some classes are gone (or maybe were renamed).

If anyone wants to try, this is what I did:

* ```cd libraries```
* ```mkdirs ../libraries_off```
* ```mv video ../libraries_off```
* ```git clone https://github.com/processing/processing-video.git video```
* ```cd video```
* ```git branch gst1-java-core```
* ```vi build.properties```
You need the Processing source code somewhere, and with the previous line you tell the video library the location of the Processing source.
* ```ant build```

I opened IntelliJ idea, which helps a lot with auto-completing and suggesting fixes. Went to ```File > Project Structure > Libraries``` and added the ```processing/core/library``` folder so it finds the core jar files.

Errors are highlighted in red, and it's easy to see what needs to be fixed. But it's not easy to see how :)

**Comment by codeanticode** [comment]
@hamoid These are the errors you are getting, right:

```
compile:
    [javac] Compiling 6 source files to /Users/andres/Documents/Processing/libraries/video/bin
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/Capture.java:40: error: package org.freedesktop.gstreamer.device does not exist
    [javac] import org.freedesktop.gstreamer.device.DeviceMonitor;
    [javac]                                        ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:47: error: package org.freedesktop.gstreamer.gl does not exist
    [javac] import org.freedesktop.gstreamer.gl.GLContext;
    [javac]                                    ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:48: error: package org.freedesktop.gstreamer.gl does not exist
    [javac] import org.freedesktop.gstreamer.gl.GLDisplay;
    [javac]                                    ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:49: error: package org.freedesktop.gstreamer.gl does not exist
    [javac] import org.freedesktop.gstreamer.gl.GLMemory;
    [javac]                                    ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:52: error: cannot find symbol
    [javac] import org.freedesktop.gstreamer.lowlevel.GstVideoAPI.VideoFrameStruct;
    [javac]                                                      ^
    [javac]   symbol:   class VideoFrameStruct
    [javac]   location: interface GstVideoAPI
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:53: error: cannot find symbol
    [javac] import org.freedesktop.gstreamer.lowlevel.GstVideoAPI.VideoInfoStruct;
    [javac]                                                      ^
    [javac]   symbol:   class VideoInfoStruct
    [javac]   location: interface GstVideoAPI
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/Capture.java:691: error: cannot find symbol
    [javac]     DeviceMonitor monitor = DeviceMonitor.createNew();
    [javac]     ^
    [javac]   symbol:   class DeviceMonitor
    [javac]   location: class Capture
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/Capture.java:691: error: cannot find symbol
    [javac]     DeviceMonitor monitor = DeviceMonitor.createNew();
    [javac]                             ^
    [javac]   symbol:   variable DeviceMonitor
    [javac]   location: class Capture
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/Capture.java:1098: error: Capture.NewSampleListener is not abstract and does not override abstract method newSample(AppSink) in NEW_SAMPLE
    [javac]   private class NewSampleListener implements AppSink.NEW_SAMPLE {
    [javac]           ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/Capture.java:1100: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/Movie.java:1066: error: Movie.NewSampleListener is not abstract and does not override abstract method newSample(AppSink) in NEW_SAMPLE
    [javac]   private class NewSampleListener implements AppSink.NEW_SAMPLE {
    [javac]           ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/Movie.java:1068: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:908: error: cannot find symbol
    [javac]     bus.connect(new Bus.NEED_CONTEXT() {
    [javac]                        ^
    [javac]   symbol:   class NEED_CONTEXT
    [javac]   location: class Bus
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:1194: error: MovieGL.NewSampleListener is not abstract and does not override abstract method newSample(AppSink) in NEW_SAMPLE
    [javac]   private class NewSampleListener implements AppSink.NEW_SAMPLE {
    [javac]           ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:1196: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:1209: error: package VideoInfoStruct does not exist
    [javac]       VideoInfoStruct.ByReference info =  org.freedesktop.gstreamer.Video.getVideoInfo(caps);
    [javac]                      ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:1209: error: cannot find symbol
    [javac]       VideoInfoStruct.ByReference info =  org.freedesktop.gstreamer.Video.getVideoInfo(caps);
    [javac]                                                                          ^
    [javac]   symbol:   method getVideoInfo(Caps)
    [javac]   location: class Video
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:1211: error: package VideoFrameStruct does not exist
    [javac]       VideoFrameStruct.ByReference frame = org.freedesktop.gstreamer.Video.mapVideoFrame(info,
    [javac]                       ^
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/MovieGL.java:1212: error: cannot find symbol
    [javac]                                            buffer, GstBufferAPI.GST_MAP_READ | GLMemory.GST_MAP_GL);
    [javac]                                                                                ^
    [javac]   symbol:   variable GLMemory
    [javac]   location: class MovieGL.NewSampleListener
    [javac] /Users/andres/Documents/Processing/libraries/video/src/processing/video/Video.java:149: error: cannot find symbol
    [javac]     Registry reg = Registry.getDefault();
    [javac]                            ^
    [javac]   symbol:   method getDefault()
    [javac]   location: class Registry
    [javac] 20 errors
```

**Comment by hamoid** [comment]
@codeanticode yes, looks like it. I tried finding solutions to some of those, but I could only go so far without studying gstreamer and its examples.

**Comment by neilcsmith-net** [comment]
@hamoid as I've just replied in an email to @codeanticode most of those errors are because of additions that were made to the gst1-java-core API that didn't get submitted upstream.  The other errors are because the API for the various AppSink listeners changed to better match GStreamer itself. Happy to help work out what needs to be added upstream and what needs to be fixed here.

**Comment by hamoid** [comment]
I think your help would be very useful @neilcsmith-net :) Not sure how I can contribute. I could keep a fork which you guys observe, we discuss, and I follow your instructions...

**Comment by neilcsmith-net** [comment]
@hamoid if you check @codeanticode gst1-java-core repo you'll see that it's 14 commits ahead and 87 commits behind upstream.  Essentially the work required is to update the changes in the fork on top of the current code, and make the relevant pull requests upstream, which might require some changes to be accepted (by me, so I'm not going to make it that hard :smile: ).

https://github.com/codeanticode/gst1-java-core
https://github.com/codeanticode/gst1-java-core/commits/master

Of the errors listed above, `Registry.getDefault()` has become `Registry.get()` and the `AppSink.NEW_SAMPLE` listener needs to return `FlowReturn.OK`.  Other than that I think the errors are all related to the missing commits from the fork.

**Comment by hamoid** [comment]
Thanks! I cloned codeanticode's, then merged upstream. There were two conflicts:

* `gstreamer/lowlevel/GstVideoAPI.java` upstream is minimal, where codeanticode's implements `VideoFrameStruct` and `VideoInfoStruct`. In the same file, `VideoInfoAbi` extends `com.sun.jna.Union`. Should I add jna?
* `gstreamer/MessageType.java` upstream uses `EXTENDED`, codeanticode's `MESSAGE_EXTENDED` (I kept upstream version)

Should I clone codeanticode, then merge back upstream, or clone upstream, and then add codeanticode's changes?

**Comment by neilcsmith-net** [comment]
@hamoid great!  Not sure what you mean by adding JNA?  JNA is already a requirement - nothing will work without it.

The changes will need to be made as pull requests upstream, but need to be split into specific functionality - ie.  at least GL in one and Device stuff in another.  Best thing is probably to stick with your fork for now and make sure everything is working, then I'll help with PR / merging upstream.

**Comment by neilcsmith-net** [comment]
Actually, re-reading your question, if you want to supply the pull requests then probably better to clone upstream, then add codeanticode's changes in two or more branches - ie. a branch for GL and a branch for Device stuff, etc.  Then make pull requests.  Note that changes you make later to the branch will be reflected in the pull request, hence suggesting using specific branches for each.

**Comment by hamoid** [comment]
Update: I made gst1-java-core build with codeanticode's changes before reading your comments. It was easy, so I'll do it again doing the branches and pull requests.

**Comment by hamoid** [comment]
How do I decide what to put on the `device` branch, and what to put on the `gl` branch? I assume 
* `../gl/` -> `gl`
* `../device/` -> `device`

But what about `../lowlevel/`, `Video*.java` and many other files in the `gstreamer/` folder?

**Comment by neilcsmith-net** [comment]
@hamoid - Thanks for looking at this! :+1: 

The `../lowlevel/` folder is the actual native bindings.  Basically, add only what is required to get the relevant branches to compile and run.  Hopefully you won't end up with an overlap there - if you do, get back to me.

Again, with the `Video*.java` and other files in the `gstreamer/`root, add in only what is required for either branch to compile.  There may be files not required by either branch - if they're not required to get the Processing Video library to work, let's deal with those later.  If there are things there that don't directly relate to GL or Device, but are needed by the Processing Video library, again get back to me.  Maybe @codeanticode can advise on exactly what is required, and what are non-requirement enhancements?

**Comment by hamoid** [comment]
After two weeks vacation, I'm back :) I'll continue tomorrow.

**Comment by hamoid** [comment]
The two branches can be found at:
* https://github.com/hamoid/gst1-java-core/commits/gl
* https://github.com/hamoid/gst1-java-core/commits/device

Both of them are building succesfully.

I did not add `VideoFrameStruct`, `VideoInfoStruct`, `VideoFrameFlags` nor these classes
```
    import org.freedesktop.gstreamer.VideoChromaSite;
    import org.freedesktop.gstreamer.VideoColorMatrix;
    import org.freedesktop.gstreamer.VideoColorPrimaries;
    import org.freedesktop.gstreamer.VideoColorRange;
    import org.freedesktop.gstreamer.VideoFlags;
    import org.freedesktop.gstreamer.VideoFormat;
    import org.freedesktop.gstreamer.VideoFormatFlags;
    import org.freedesktop.gstreamer.VideoInterlaceMode;
    import org.freedesktop.gstreamer.VideoMultiviewFlags;
    import org.freedesktop.gstreamer.VideoMultiviewMode;
    import org.freedesktop.gstreamer.VideoTileMode;
    import org.freedesktop.gstreamer.VideoTransferFunction;
```

In a nutshell, I used the first 4 commits from codeanticode, plus converted two instances of List to List<String>. What would be the next step?

**Comment by hamoid** [comment]
Trying to compile the Processing Video library I now see that the items I skipped are required, for instance VideoInfoStruct, VideoFrameStruct, GLMemory and others (all in MovieGL.java).

**Comment by neilcsmith-net** [comment]
@hamoid At a guess those changes belong in the GL branch.  If they're required to make use of the GL features then add them as part of that pull request.  Likewise, if they're classes used here to support device probing in the Processing library, add them to the Device branch.  I'm hopeful we won't find an overlap in changes there!

Leave out any classes not currently required by the Processing library for now, and we'll mop up those afterwards.

Thanks, Neil

**Comment by villares** [comment]
:(((((((
Any solution for people not skillful compiling libraries from source?

**Comment by hamoid** [comment]
I suddenly joined a summer course on VR for the whole month of July. That's why I couldn't make any progress on it. At the end of this week I'm free again, I plan to take a look at it then.

**Comment by hamoid** [comment]
I managed to play a video! Which made me happy after about 8 hours shuffling branches and repos with git, trying to cherry pick the codeanticode changes into the 'gl' and 'device' branches, while having it build, and maintaining the original commits. At the end I got tired and packed everything into larger commits. Unfortunately I can't spend much more time with this.

I had to make some changes in the video library. They can be seen here: https://github.com/hamoid/processing-video/tree/gst1-java-core

Here's my gst1-java-core https://github.com/hamoid/gst1-java-core with several branches: one with the `device` changes, one with the `gl` changes, and `glAndDevice` contains both sets of changes to compile the library for Processing.

The examples that do *not* use `.jump()` work. The error with `jump` looks like this:
```
UnsatisfiedLinkError: Error looking up function 'gst_video_frame_rate': /usr/lib/libgstvideo-1.0.so.0: undefined symbol: gst_video_frame_rate
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
```

**Comment by hamoid** [comment]
I leave here my notes in case I or someone else needs them later

```
  https://github.com/processing/processing-video/issues/71
  https://github.com/hamoid/gst1-java-core
  
  clone 
  https://github.com/gstreamer-java/gst1-java-core
  create device branch
  create gl branch

  Doing:
  add changes from https://github.com/codeanticode/gst1-java-core
    affecting gl/ and device/

  I work on two folders:

  cd /home/funpro/src/gst1-java-core 
  $ mvn package # compile gstreamer

  cd /home/funpro/Desktop/edu/src/processing/libraries/video
  $ ant build $ compiled video library

  git remote add upstream git@github.com:gstreamer-java/gst1-java-core.git
  git remote add codeanticode git@github.com:codeanticode/gst1-java-core.git
  git fetch codeanticode
  git fetch upstream
  git checkout upstream/master
  git checkout codeanticode/master
  git branch -a
  git checkout -b gl
  git checkout -b device
  git push origin device
  git checkout gl
  git push origin gl

  git checkout gl
  git cherry-pick -n 6e1a89db19a0a7089ecfe69c177fd240d7b03020
  git cherry-pick -n e3357dce543986fefacf059f7cd96db6a71e1940
  # remove lowlevel/*device*
  # commit files
  # ...
  # cherry-pick c25c (CallerOwnsReturn)

  git checkout device
  git cherry-pick -n 3f2e778ae099c2b811503e3fdc951006eac9213b
  # add these 4 files
     src/org/freedesktop/gstreamer/lowlevel/GstDeviceAPI.java
     src/org/freedesktop/gstreamer/lowlevel/GstDeviceMonitorAPI.java
     src/org/freedesktop/gstreamer/lowlevel/GstDeviceProviderAPI.java
     src/org/freedesktop/gstreamer/lowlevel/GstDeviceProviderFactoryAPI.java
  # from e3357dce543986fefacf059f7cd96db6a71e1940 so
  # mvn package compiles.
  # patch GstDeviceProviderAPI.java (just add <String>)
  git add src/org/freedesktop/gstreamer/lowlevel/GstDevice*java

  Current status: 
  - branch device ready
  - branch gl continue with 9 8 7 6 ... 1
  - both device and gl build, but the produced jar file does not work
    inside the video library because GLMemory is missing (probably
    others)
  - to solve the last issue, I add all gl/ folder changes
  cp target/gst1-java-core-0.9.1-SNAPSHOT.jar ~/Desktop/edu/src/processing/libraries/video/library/
  - now VideoFrameStruct and VideoInfoStruct are missing
  to add them I need 
  9: Video.java, VideoFrameFlags.java, GstVideoAPI.java 
  8: all but gl/
  7: all but gl/
  6: all (gl messages)
  5: all (one file)
  4: all

# commits by codeanticode and affected folders
1  Vid* lowlevel/           3d7a024fc02bd333111056573e4856ff6921662b
2  Vid* lowlevel/           5db7f08cdbdc746ab26967a8c49de683aec1c8a6
3  Vid* lowlevel/           d0f37351e5f03452b7d85acc793ebd34d95ea9f9
4  Vid* lowlevel/           44e30ec5f271093fbd7b4fe908778360a050449d
5  lowlevel/                45b7f5e2be07225d565ddb426420ed9eacabd94a
6  * lowlevel/              a799fe94dd7fad92ba55af3075ef80b73df04503
7  Vid* lowlevel/ gl/       cd20c7341eace0416f3d6caad9aedcfd22e3df51
8  Vid* lowlevel/ gl/       a32dacee18f6b31c6e21d007d8039c956c91b38f
9  Vid* lowlevel/ gl/       6952d8e2a1f190128eee025e5206d665f4672277
---
10 lowlevel/                872a81fe4086ecb1dc095505728a938e4c70c25c
11 device/                  3f2e778ae099c2b811503e3fdc951006eac9213b
12 gl/                      6e1a89db19a0a7089ecfe69c177fd240d7b03020
13 lowlevel/                e3357dce543986fefacf059f7cd96db6a71e1940

# Files changed both by codeanticode and upstream:

src/org/freedesktop/gstreamer/Bus.java ! (add only) DONE
src/org/freedesktop/gstreamer/Video.java ! (add only) DONE
src/org/freedesktop/gstreamer/MessageType.java ! (add only) DONE
src/org/freedesktop/gstreamer/lowlevel/GstVideoAPI.java ! (big change) DONE
src/org/freedesktop/gstreamer/lowlevel/GstBufferAPI.java ! (makes not final, adds) DONE
src/org/freedesktop/gstreamer/lowlevel/GstMessageAPI.java ! (add only) DONE


# List of all commits and which files they affect. 
  (!) indicates an upstream file is affected.
  (own) means it's a new file, not in upstream.

# 1. removed some debug printouts
src/org/freedesktop/gstreamer/Video.java !
src/org/freedesktop/gstreamer/lowlevel/GstVideoAPI.java !

# 2. Don't use VideoInfoStruct.ByReference for VideoFrameStruct.info
src/org/freedesktop/gstreamer/Video.java !
src/org/freedesktop/gstreamer/lowlevel/GstVideoAPI.java !

# 3. more refs
src/org/freedesktop/gstreamer/Video.java !
src/org/freedesktop/gstreamer/lowlevel/GstBufferAPI.java ! (makes not final, adds)
src/org/freedesktop/gstreamer/lowlevel/GstVideoAPI.java ! 

# 4. all structs should be ByReference.
src/org/freedesktop/gstreamer/Video.java !
src/org/freedesktop/gstreamer/lowlevel/GstVideoAPI.java ! 

# 5. use PointerByReference
src/org/freedesktop/gstreamer/lowlevel/GstMessageAPI.java ! (change own line)

# 6. added gl messages
src/org/freedesktop/gstreamer/Bus.java ! (add only)
src/org/freedesktop/gstreamer/MessageType.java ! (add only)
src/org/freedesktop/gstreamer/lowlevel/GstMessageAPI.java ! (add only)

# 7. adding new Java-style methods in Video API, use ints instead of enums
src/org/freedesktop/gstreamer/Video.java !
src/org/freedesktop/gstreamer/VideoFormat.java (own)
src/org/freedesktop/gstreamer/gl/GLMemory.java (own)
src/org/freedesktop/gstreamer/lowlevel/GstVideoAPI.java ! 

# 8. added remaining structs (own, except lowlevel/)
src/org/freedesktop/gstreamer/VideoChromaSite.java
src/org/freedesktop/gstreamer/VideoColorMatrix.java
src/org/freedesktop/gstreamer/VideoColorPrimaries.java
src/org/freedesktop/gstreamer/VideoColorRange.java
src/org/freedesktop/gstreamer/VideoFlags.java
src/org/freedesktop/gstreamer/VideoFormat.java
src/org/freedesktop/gstreamer/VideoFormatFlags.java
src/org/freedesktop/gstreamer/VideoInterlaceMode.java
src/org/freedesktop/gstreamer/VideoMultiviewFlags.java
src/org/freedesktop/gstreamer/VideoMultiviewMode.java
src/org/freedesktop/gstreamer/VideoTileMode.java
src/org/freedesktop/gstreamer/VideoTransferFunction.java
src/org/freedesktop/gstreamer/gl/GLAPI.java (own)
src/org/freedesktop/gstreamer/lowlevel/GstVideoAPI.java ! 

# 9. adding required GstVideo API 
src/org/freedesktop/gstreamer/Video.java  !
src/org/freedesktop/gstreamer/VideoFrameFlags.java (own)
src/org/freedesktop/gstreamer/gl/GLContext.java (own)
src/org/freedesktop/gstreamer/lowlevel/GstDeviceProviderAPI.java (own)
src/org/freedesktop/gstreamer/lowlevel/GstVideoAPI.java ! 

---

# 10. added CallerOwnsReturn import
src/org/freedesktop/gstreamer/lowlevel/GstGLContextAPI.java (own)

# 11. added device probing classes (own)
src/org/freedesktop/gstreamer/device/Device.java
src/org/freedesktop/gstreamer/device/DeviceMonitor.java
src/org/freedesktop/gstreamer/device/DeviceProvider.java
src/org/freedesktop/gstreamer/device/DeviceProviderFactory.java 

# 12. added gl classes (own)
src/org/freedesktop/gstreamer/gl/GLAPI.java
src/org/freedesktop/gstreamer/gl/GLContext.java
src/org/freedesktop/gstreamer/gl/GLDisplay.java
src/org/freedesktop/gstreamer/gl/GLDisplayType.java
src/org/freedesktop/gstreamer/gl/GLPlatform.java
src/org/freedesktop/gstreamer/gl/GLWindow.java 

# 13. added new lowlevel classes (own)
src/org/freedesktop/gstreamer/lowlevel/GThread.java
src/org/freedesktop/gstreamer/lowlevel/GstContext.java
src/org/freedesktop/gstreamer/lowlevel/GstDeviceAPI.java
src/org/freedesktop/gstreamer/lowlevel/GstDeviceMonitorAPI.java
src/org/freedesktop/gstreamer/lowlevel/GstDeviceProviderAPI.java
src/org/freedesktop/gstreamer/lowlevel/GstDeviceProviderFactoryAPI.java
src/org/freedesktop/gstreamer/lowlevel/GstGLAPI.java
src/org/freedesktop/gstreamer/lowlevel/GstGLContextAPI.java
src/org/freedesktop/gstreamer/lowlevel/GstGLDisplayAPI.java 


https://stackoverflow.com/questions/1405030/using-git-how-can-i-selectively-pull-merge-changes-from-anothers-fork
```

**Comment by neilcsmith-net** [comment]
Thanks @hamoid I've pulled your work into two branches in my fork of the main repo and will work on finishing them off.

It looks like the code in `jump()` relying on getting the framerate from PlayBin needs pulling out for now. Not sure I entirely see the reason for using it.  I'll pull out the non-working code from PlayBin and look for an alternative if it's required.

**Comment by rich-gg** [comment]
Hi there

been trying to run a sketch using processing.video on a fresh Ubuntu install for some days and couldn't get it to work, even with the help of @neilcsmith-net 
Doing this
`sudo apt-get install gstreamer0.10-plugins-good`
doing this 
`sudo apt-get install ubuntu-restricted-extras`
and this
`sudo apt-get install gstreamer0.10-ffmpeg gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad gstreamer0.10-bad-multiverse`
Doing the third one, I got some "has no installation candidate" answers.

Do you guys have a tip on how I could get this to work ?

cheers

**Comment by hamoid** [comment]
@rich-gg I would first figure out which one of the packages in step 3 is failing, then search online for that package + ubuntu. Maybe this is related: https://askubuntu.com/questions/575869/how-do-i-install-gstreamer0-10-ffmpeg-on-ubuntu-14-10#575888

I hope we can get the gstreamer1.0 video library working soon, which would avoid you doing any such hacks.

**Comment by neilcsmith-net** [comment]
@hamoid @rich-gg Step 3 will likely fail on all of those packages - only `gstreamer0.10-plugins-good` seems to be packaged for 16.04.

**Comment by rich-gg** [comment]
@neilcsmith-net
I followed @hamoid tips and it did work like a charm 

```
sudo add-apt-repository ppa:mc3man/gstffmpeg-keep
sudo apt-get update
sudo apt-get install gstreamer0.10-ffmpeg
```
and I'm a happy camper now !

Thank you guys :D

**Comment by hamoid** [comment]
@neilcsmith-net hi! Any progress on this? I'll be soon giving a workshop on Processing + webcams. For now I'm going to see if I can go back to 0.10 somehow.

**Comment by neilcsmith-net** [comment]
@hamoid sorry, I've not had a chance to complete working through and integrating all the code into the main gst1-java-core repo yet - busy month! Few issues found that need fixing, although nothing major. Will try and find time next week. That doesn't address the need to update the Processing library on top though.  Haven't you got a working fork anyway?  Can't you use that?

**Comment by hamoid** [comment]
Hi @neilcsmith-net , I know how hard it is to find time!

I had successfully played video, but the workshop is about webcams. 

`cam.list()` was failing, but I just realized I can initialize the camera with `cam = new Capture(this);` without specifying dimensions and without using `.list()`, so that gets me going. Good enough for now! :)

**Comment by neilcsmith-net** [comment]
@hamoid I got the required code for listing devices working from the code you had, although had to make a few fixes - I'm on a different machine at the moment so can't check what I had to do. Still, short term you could hack the `Capture` class to use `autovideosrc` as the GStreamer element. Depends what OS your users are on - some of the capture elements in GStreamer have changed too.

**Comment by james-mcelwain** [comment]
I was able to use the information here to get everything working on Arch, thanks y'all!

**Comment by gohai** [comment]
@hamoid @neilcsmith-net Fantastic work on this issue, much appreciated! I started playing around to see if we can get this to a releasable state, and finally kiss 0.10 GStreamer goodbye for good. You find my WIP tree here (currently based on @hamoid's `glAndDevice` build): https://github.com/gohai/processing-video/commits/testing

BTW: Andres and I decided to rip out the half-baked GL code, since this was superseded by my [GL Video](https://github.com/gohai/processing-glvideo) library for the Raspberry Pi. So this means we can leave aside the `Gl`/`opengl` branch of `gst1-java-core` for now.

**Comment by neilcsmith-net** [comment]
@gohai great news!  I am looking at pulling in the device probing stuff into a new gst1-java-core release soon.  My personal fork has at least one memory leak fix.  Let's make sure you have exactly what you need and get it into a full 0.9.1 release on Maven Central - I would *really* like you not to release with a snapshot! :smile: 

In terms of the device probing, when testing this I was confused why the video library is using a listener on the monitor bus rather than just calling getDevices()?  I have a working example with device selection that seems to do what you'd want to do?

The OpenGL code will make its way into gst1-java-core very soon.  While I agree that it would be good to get a feature comparable version of the Video library working with GStreamer 1.x sooner rather than later, the GL stuff is useful on other platforms too, so be good to not ignore completely.  I for one will be looking to get OpenGL video support across as many platforms as possible into Praxis LIVE soon, so there's room for collaboration there.

**Comment by neilcsmith-net** [comment]
@gohai quick follow up - I think everything you need is now in the master branch of gst1-java-core. Please check and I'll release 0.9.1 ASAP.

**Comment by gohai** [comment]
@neilcsmith-net 
I updated the gst1-java-core to your current master - thanks! Will definitely try to track your changes there and go for released versions.

Device probing: I made a note. But the much bigger issue for us is that GStreamer doesn't seem to have any DeviceMonitor backend for video devices on macOS, and I believe also Windows, currently. Which means that for the majority of P5 users we can't do `list()` :/

With your latest gst1-java-core we're still running into this incompatibility with `playbin.getVideoSinkFrameRate()`, btw. I stopped using it on our side for now.

**Comment by neilcsmith-net** [comment]
@gohai OK, I'll look to release 0.9.1 this coming week.  I'll do some looking into device probing - latest GStreamer release notes suggest it should return something.

`playbin.getVideoSinkFrameRate()` is on my list to look at or remove. It currently relies on a changed API from GStreamer 0.10 -> 1.x.  I haven't checked but I think you can get the framerate from the caps in the AppSink where you're currently getting width and height - assuming the struct returns `Fraction` OK?!

Return `FlowReturn.OK` not `null` or you may run into odd problems on certain platforms (the API was changed because of a bug report around this).

**Comment by gohai** [comment]
@neilcsmith-net I believe I saw something along those lines as well in the release notes, but this seems to only have been enumeration for `Audio/Sink` and `Audio/Source` on macOS - at least that are the only two devices that show up for me when I run `gst-device-monitor-1.0`.

Thanks for the pointers regarding framerate, I'll look into it.

**Comment by gohai** [comment]
@neilcsmith-net Getting the framerate from the caps worked out. I also made the change wrt `FlowReturn.OK`. Thanks!

I noticed two things: excessive `seek()` calls (via Processing's `jump()`, e.g. in the `Scratch`) examples make the video become unresponsive after a while. Could there be a memory leak, or something sinister going on there? There is no logic to when it happens - we're not attempting to seek beyond eos, or something like that. Execution continues happily after the fateful `seek()`, but the `NewSampleListener` just won't get called any longer...

Any ideas?

The second observation was that I can't seem to be able to get a video file to play backwards in 1.x, and I remember that this issue also came up when I wrote the GL Video library. Curious: have you ever been successful doing that in Praxis Live?

**Comment by neilcsmith-net** [comment]
@gohai yes, both seek and reverse playback working fine (and you've seen it in action :wink: ). Although I'll test with the same video as the scratch example to be sure. The most relevant code is here - https://github.com/praxis-live/praxis/blob/master/praxis.video.gst1/src/net/neilcsmith/praxis/video/gst1/components/PlayBinDelegate.java#L126

Some things to note

- the behaviour in the Scratch example of calling play, jump, pause is weird and might be causing an issue - try re-enabling the newPrerollListener and just scratching in the pause state. (if you keep it playing now does it continue working?)
- all my calls down to GStreamer use `Gst.getExecutor()` to take things off the main Processing animation thread - `getState()` blocks (note my use of the timeout variant), although if you're sure execution is still happening afterwards that might not be the the problem with that particular example. It's still better not to block the animation thread waiting for GStreamer to do its thing though!
- note the different seek calls for when the rate is reversed - you need to set the from and to values correctly (surprised this worked with 0.10, although maybe that behaviour did change)
- a rate of zero will throw errors - note the hacky workaround! :smile:

**Comment by neilcsmith-net** [comment]
@gohai for info, `0.9.1` is now tagged and available from the GitHub releases tab or Maven Central. Let me know if you run into any issues. Over to you now! :smile: Best wishes, Neil

**Comment by gohai** [comment]
@neilcsmith-net Thanks, integrated it here: https://github.com/gohai/processing-video

**Comment by gohai** [comment]
All: I built on top of the community came up with (thanks @hamoid @neilcsmith-net), and - 43 commits later - arrived at a version of the library that works with GStreamer 1.0 on all platforms and might be good enough for general use.

All details, including a link to a ZIP file for testing, can be found in this PR: #84 

Please see if this works for you, and - if not - please consider sending small, self-contained PRs on top. I hope this way we can move this thing forward together!

**Comment by drnn1076** [comment]
Many Thanks to all of you for all your hard work on this library! 
I can report that I downloaded the @gohai code, copied it to the library folder and it works in Opensuse Tumbleweed with processing 3.3.7

**Comment by codeanticode** [comment]
Version 2.0 of the library (beta packages available [under releases](https://github.com/processing/processing-video/releases)) uses gstreamer 1.x, so closing this issue.
