### ISSUE TITLE
Not working on MacOS 10.12.5

### ISSUE THREAD

**Issue by dbdbking** [processing/processing-video#75]
NullPointerException on:

`String[] cameras = Capture.list();`

**Comment by hamoid** [comment]
Which version of Processing? Do any of the webcam Processing Examples work?

**Comment by stephiescastle** [comment]
I'm having the same issue. Processing 3.3.6, Java 8. Also had same issue in Processing 3.3.5.

**Comment by dbdbking** [comment]
The issue was caused by my LeapMotion....
