### ISSUE TITLE
Export doesnt working..

### ISSUE THREAD

**Issue by Amitnzri** [processing/processing-video#78]
the extended application doesn't works when using the video library.
checked on mac and PC.

**Comment by hamoid** [comment]
Hi! Can you provide more details? A minimal example program that fails? OS version? Processing version?

**Comment by Amitnzri** [comment]
Some how it fixed by itself  
so I guess the problem was in my pc, thank you.
Great library love it!


Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by hamoid** [comment]
Great to hear! Feel free to close the issue :)

**Comment by Amitnzri** [comment]
can I ask how does your library communicate with the webcam? is it some system api? I searched for the answer how to do this without libraries like yours and I didn’t figured it out..
thanks again



Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by hamoid** [comment]
I'm not one of the developers, I was only trying to make sure that issues provide enough info to get them solved :) You can see the source code of Capture.java here https://github.com/processing/processing-video/blob/master/src/processing/video/Capture.java

I think on that file on line 62 you can see the approaches it uses on different platforms to access the webcam. I believe it uses gstreamer and qtkitvideo (Mac), ksvideo (Win) or v4l2 (Linux)

**Comment by Amitnzri** [comment]
haha, any way thank you very much for the help.


Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
