### ISSUE TITLE
Video playback (even examples) shows black screen, no error messages

### ISSUE THREAD

**Issue by davismattg** [processing/processing-video#79]
Ever since upgrading to OS X 10.12.5, none of my sketches involving playing movie files stored locally work any more. They all just show a black screen. Even the examples included with the Processing Video Library don't work. It seems as though it can't load the movie properly, as movie.duration() always returns 0.0.

I have installed the latest GSVideo library correctly but that didn't make a difference. I've also uninstalled Processing several times, and tried on both 3.3.4 and 3.3.5. Everything worked great just a few months ago, before updating OS X.

Any suggestions would be greatly appreciated! Thanks.

**Comment by lastfuture** [comment]
I have the same problem in 10.13 Beta (17A352a)

**Comment by lastfuture** [comment]
Quick update: I've found what caused the problem for me. Documents in iCloud. It turns out my Documents/Processing folder wasn't fully downloaded to my mac. After manually initiating the download of the rest of the files it started working again.
