### ISSUE TITLE
version 2.0-beta1 Webcam Capture doesn't seem to work on Windows10-1709

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing-video#89]
The version 2.0-beta1 of the library doesn't seem to work in Windows 10, version 1709. When loading the Getting Started Capture example (tried also LivePockey) even the 2 connected camera's (build in and UVC Webcam) are not shown (it doesn't even list the camera's in the console). 

I've tested the camera's with VLC (Open Capture Device > USB Video Device). 

The current release (1.01) works (although it throws red GStreamer warnings). 

I know that Microsoft messed with camera support in the Win10 Anniversary Edition and I did several checks related to that (https://www.drivethelife.com/windows-10/fix-laptop-camera-not-working-windows-10.html). I have to say that Processing doesn't show up in Apps that should be allowed to check the camera. 

The strange thing is that I had version 2.0 working one time (before the update I think in version 16..), it showed the 2 camera's (not the whole list with resolutions like in the 1.01 version) and I could capture it. 

I run Processing 3.3.6. 

--
On OSX the library seems to work good. I can access even the MPJEG (or is it H264) streams on high resolution (1600*1200 at 30fps) with the Logitech Quickcam Pro 9000 for Mac.

**Comment by kasperkamperman** [comment]
I've found by accident a workflow how to make it work, however there is certainly something wrong. - I do "Export Application..." and I export it for Windows. 
- Wait till the export is finished. 
- I run the Sketch again by pressing the play button (so I don't run the exported applications). 
- Then the camera capture works and keeps working (starting and stopping the sketch multiple times). 

However when I restart Windows and run the sketch again it won't work (even if the exported applications are present). Only when do the above steps again I can make it work.

**Comment by codeanticode** [comment]
@kasperkamperman Could you try the [latest beta](https://github.com/processing/processing-video/releases/tag/r5-v2.0-beta3) and confirm if this problem is solved?

**Comment by kasperkamperman** [comment]
@codeanticode Sorry I don't have access to a windows10 system. I'll keep this in my action list, but I think I can start testing it earliest in September.

**Comment by codeanticode** [comment]
I have been testing the latest version of the video library with GStreamer 1.16.0 on Windows, using several different webcams, and so far is working well. I will close this issue, but feel free to comment if you find any problems with camera capture. The last beta before the stable release will be available for download shortly.
