### ISSUE TITLE
GStreamer Critical 

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-video#9]
<a href="https://github.com/aschenbrennerin"><img src="https://avatars.githubusercontent.com/u/6683504?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aschenbrennerin](https://github.com/aschenbrennerin)**
_Friday Feb 14, 2014 at 15:48 GMT_
_Originally opened as https://github.com/processing/processing/issues/2360_

---

Hey,

I'm using Processing 2.1.1 64 bit with a simple webcam viewer example:

```
import processing.video.*;

Capture video;

void setup() {
  size(1300,900);
  // available is name=Microsoft LifeCam Studio,size=1280x720,fps=30
  video = new Capture(this,1280,720,30);
  video.start();
}

void draw() {
  if (video.available()) {
    video.read();
  }
 image(video,0,0);
}
```

I've now encountered a problem with high resolution camera pictures: they aren't displayed and I get the following error message after a while. Camera stream with a lower resolution (or even with a lower framerate) are displayed properly.

```
(javaw.exe:6520): GStreamer-CRITICAL **:
Trying to dispose element rgb, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.
```

**Comment by Bazmundi** [comment]
an interim measure may be at: https://github.com/processing/processing-video/issues/32

**Comment by codeanticode** [comment]
This should be addressed with the latest v2 betas that use GStreamer 1.x
