### ISSUE TITLE
Video Library Release 3 (version 2.0-beta1) - multiple camera's MacOs

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing-video#93]
I got this message when trying to list the camera's: `Device enumeration is currently not supported on your platform.`

I know this version is still in beta and in the capture.java file I've found that device enumeration is not yet implemented for MacOs, which is why this message is displayed. 

It now works with the build in FaceTime camera, however because devices are not listed, I'm not able to select the external webcam (which I can in the current release version of the library). 

Is it possible at all to select an external webcam with this version on MacOS? If yes, how would I do that then? 

My main reason is to test is H264 webcam streams are already supported (is that the case with this version?).

**Comment by iantech** [comment]
I have the same issue. Did you find a workaround?

**Comment by codeanticode** [comment]
The gstreamer capture plugin for mac now lists supports device enumeration: https://github.com/processing/processing-video/commit/40c15655143550a5130098970b05eb57a0a3e2c7

Beta 3 will incorporate this.
