### ISSUE TITLE
Update gst1-java-core to 0.9.3+

### ISSUE THREAD

**Issue by neilcsmith-net** [processing/processing-video#94]
Just a heads up as I noticed you've still got 0.9.1 included - there have been a few key bug fixes in the last two releases that might be relevant.  There are also a couple of minor API changes, which probably won't affect you, but if they do are minor to update.  Expect a few more before we get to 1.0 too!

While I appreciate how much work Gottfried put into this, it would be nice to get a credit back to PraxisLIVE and others involved in this too - just sayin'! :smile:

**Comment by cacheflowe** [comment]
I just upgraded to 0.9.3 locally and it seems to work great. I'm looking forward to Processing Video beta v2 getting to full release - videos play *so* much better with this upgraded video library!

**Comment by cacheflowe** [comment]
When I said it works great, that was mostly true. I've found a recurring problem that I believe happened with both of the versions mentioned here, described in this new Issue: https://github.com/processing/processing-video/issues/104

**Comment by codeanticode** [comment]
@cacheflowe @neilcsmith-net Just updated to gst1-java-core 1.0.0-beta2. I had to make some minor API changes (see https://github.com/processing/processing-video/commit/6c7c7165bdbb6c9796fab7cfefca84fd1a59406f#diff-a3fe951979ed2b4a822789e4e3ce608a, https://github.com/processing/processing-video/commit/6c7c7165bdbb6c9796fab7cfefca84fd1a59406f#diff-c357ba124bf72dcca1be6683573ad1b5) and both movie playback and camera capture seem to work well, although I did not test extensively. 

Since we are at it, could you give some help? I have created a new label "v2" to tag issues that should be fixed in the 2.0 version of the library. I'm doing a quick scanning to try to separate current from outdated issues, this would help a couple of GSOC candidates who submitted proposals to work on the video library update.

**Comment by neilcsmith-net** [comment]
@codeanticode looks about right. It looks like you're still using JNA 4.2 here though?  This _might_ work in some cases but the minimum required JNA is 5.2.  Might be good to look at Maven / Gradle, or at least the Ant Ivy plugin, to pull in the dependencies rather than committing them?  gst1-java-core v1 final will be out in a few days.

**Comment by codeanticode** [comment]
Cool. I will look into the JNA dependency. What's the status of the hardware-accelerated playback? People have reported that the beta1 of the video library already was much better at playing 4K content than the older one, so perhaps gstreamer already handles this? In an case, are there ways to get the frames directly into OpenGL textures using gst1-core? If you have some code that demonstrates this, you can just point me to it. Thank you!

**Comment by neilcsmith-net** [comment]
@codeanticode what do you mean? There isn't OpenGL context sharing, but then there wasn't in the old 0.10 bindings either?!  If you mean directly pushing the native buffer to texture upload then yes, that's supported and been doing that in PraxisLIVE since I first did this in 2015.

You could have a look at - 

- https://github.com/praxis-live/praxis/blob/master/praxis.video.gstreamer/src/org/praxislive/video/gstreamer/components/PImageSink.java#L141 
- https://github.com/praxis-live/praxis/blob/master/praxis.video.gstreamer/src/org/praxislive/video/gstreamer/components/PImageSink.java#L117

Key thing is where before you might keep a Buffer reference you should now keep a Sample reference - I keep one and dispose on swap under lock.  The PImage here is not the same as a Processing PImage, but hopefully makes sense. First link is happening in the GStreamer thread, second in the Processing animation thread.  It's somewhat different and more efficient API as the PImage is only valid during the callback into the "sketch" (Consumer<PImage>) - ie. this is the user side API - https://github.com/praxis-live/praxis/blob/master/praxis.video.gstreamer/src/org/praxislive/video/gstreamer/components/VideoPlayerComponent.java#L106 Could be good if/when Processing gets method references! Always disliked Movie _being_ a PImage rather than being a source of PImages.

GStreamer 1.x is definitely better performing - why I did the fork in the first place, because I was working with some embedded kit and the difference was dramatic.  I have a feeling even if the AppSink handoff is on the CPU, the GPU decoders may still be in use.

**Comment by codeanticode** [comment]
What I meant is directly pushing the native buffer to texture upload. Thanks for the links!

**Comment by cacheflowe** [comment]
@codeanticode @neilcsmith-net Please let me know how/when I can help test a beta v2. I'm unfortunately not yet helpful in fixing these low-level issues (I've never compiled the library or core), but I've done a lot of recent production work with the video library, so I can stress test it pretty well :) I'll keep my eyes on this progress and would like to help!

**Comment by codeanticode** [comment]
@cacheflowe testing would definitely be very helpful, thank you!
