### ISSUE TITLE
Can't install the video library

### ISSUE THREAD

**Issue by kantel** [processing/processing-video#95]
When I trie to install the video library via the »Tool«-Menu it startet (see screenshot below) but after a few minutes it stops with the error message `Verbindungs-Wartezeit beim Download von Video überschritten`, which simple means »Timeout« (I think).

![timeout](https://user-images.githubusercontent.com/1219909/40623783-f6f378fc-62a8-11e8-84f5-3a136da5ad6a.png)

My Environment: Processing 3.3.7 on macOS X, 10.9.5 and a stable Internet Connection through the »Deutsches Forschungs Netz« (DFN)  -- english »German Research Network«

(Pls excuse my bad (d)english)

**Update**: It's solved (at least for me). After around 30 tries I got the library installed.

**Comment by codeanticode** [comment]
Glad you figured it out!
