### ISSUE TITLE
a possible mistakes in examples on the FrameRate

### ISSUE THREAD

**Issue by naliece** [processing/processing-video#96]
When put the **movie.framRate** in the setup function, nothing will change.
I assume that may should be put in the draw function to make it works.

**Comment by codeanticode** [comment]
You can set the framerate of your movie by calling movie.frameRate(fps), where fps is your desired fps. You can also use movie.speed(s) so speed up or slow down the playback of the movie by a given factor. You can post your question on the forum to get more information.
