### ISSUE TITLE
Detailed Installation Instructions to Install Video Library Version 2.0-beta1 on Processing 3.4 Needed

### ISSUE THREAD

**Issue by vepicurean** [processing/processing-video#98]
If anyone has details instructions to install the version 2.0-beta1 video library on Processing 3.4 it would be appreciated. The standard manual install instructions for libraries on Processing 3.4 are not working for us on Ubuntu Server 18.04

Thanks.

**Comment by liffiton** [comment]
This is a late comment, but I can report that manual installation worked for me in Ubuntu 18.04 (desktop, if that matters):

1. Download `video-2.0-beta1.zip` from [Releases](https://github.com/processing/processing-video/releases).
2. Go to the `libraries` folder in your sketchbook folder (check Processing preferences if you're not sure where your sketchbook is).
3. Delete any existing `video` folder you find (just to make sure old versions of the library and any files are removed).
4. Unzip the `video-2.0-beta1.zip` file into the `libraries` folder.  This should create a new `videos` folder.

With that, the library worked for me in Ubuntu 18.04 with Processing 3.5.3, or at least the `processing.video.Capture` part of it did.

**Comment by codeanticode** [comment]
@liffiton thanks for answering the question. @vepicurean note that GitHub is meant for filing bug reports, not support questions. The Processing wiki has an entry on manual library installation:

https://github.com/processing/processing/wiki/How-to-Install-a-Contributed-Library
